desktop=C:\\Users\\Administrator\\Desktop\\
jpdir=i:\\brmjp\\
endir=i:\\brmen\\
outdir=i:\\isopatcher\\

#desktop=C:\\Users\\me\\Desktop\\
#jpdir=d:\\hanhua\\brmjp\\
#endir=d:\\hanhua\\brmen\\
#outdir=d:\\hanhua\\isopatcher\\

